mysite/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.home, name='home'),
    path('upload', views.upload, name='upload'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

mysite/myapp/models.py
from django.db import models

# Create your models here.


class League(models.Model):
    number = models.IntegerField()

    def __str__(self):
        return str(self.number)


class Year(models.Model):
    number = models.IntegerField()

    def __str__(self):
        return str(self.number)


class Team(models.Model):
    string = models.CharField(max_length=32)

    def __str__(self):
        return self.string


class Participation(models.Model):
    number = models.IntegerField()

    def __str__(self):
        return str(self.number)


class Person(models.Model):
    string = models.CharField(max_length=32)

    def __str__(self):
        return self.string


class Song(models.Model):
    string = models.CharField(max_length=32)

    def __str__(self):
        return self.string


class Parent(models.Model):
    league = models.ForeignKey(
        League, on_delete=models.SET_NULL, null=True, related_name='related_League')
    year = models.ForeignKey(
        Year, on_delete=models.SET_NULL, null=True, related_name='related_year')
    team = models.ForeignKey(
        Team, on_delete=models.SET_NULL, null=True, related_name='related_Team')
    participation = models.ForeignKey(
        Participation, on_delete=models.SET_NULL, null=True, related_name='related_Participation')
    person = models.ManyToManyField(
        Person, related_name='related_Person')
    song = models.ForeignKey(
        Song, on_delete=models.SET_NULL, null=True, related_name='related_Song')

    def __str__(self):
        return self.song.string

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

import csv
import os
from io import TextIOWrapper
from .models import League, Year, Team, Participation, Person, Song, Parent
from django.shortcuts import render
from .models import Parent


def home(request):
    filtered_data = None

    if request.method == "POST":
        select_option = request.POST.get('selectOption')
        text_box_value = request.POST.get('textBox')

        if text_box_value:
            try:
                if select_option == 'league':
                    filtered_data = Parent.objects.filter(
                        league__number=int(text_box_value))
                elif select_option == 'year':
                    filtered_data = Parent.objects.filter(
                        year__number=int(text_box_value))
                elif select_option == 'team':
                    filtered_data = Parent.objects.filter(
                        team__string=str(text_box_value))
                elif select_option == 'participation':
                    filtered_data = Parent.objects.filter(
                        participation__number=str(text_box_value))
                elif select_option == 'person':
                    filtered_data = Parent.objects.filter(
                        person__string=str(text_box_value))
                elif select_option == 'song':
                    filtered_data = Parent.objects.filter(
                        song__string=str(text_box_value))
                else:
                    # 未知の選択肢に対する処理
                    pass
            except ValueError:
                # textBox の値が整数に変換できない場合のエラーハンドリング
                pass

    context = {'data': filtered_data}
    return render(request, 'home.html', context)


# ----- 名簿登録 -----
def upload(request):
    if 'csv' in request.FILES:
        form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
        csv_file = csv.reader(form_data)

        for line in csv_file:
            league, _ = League.objects.get_or_create(number=line[0])  # 大会
            year, _ = Year.objects.get_or_create(number=line[1])  # 年
            team, _ = Team.objects.get_or_create(string=line[2])  # 組
            participation, _ = Participation.objects.get_or_create(
                number=line[3])  # 回数
            person, _ = Person.objects.get_or_create(string=line[4])  # 人
            song, _ = Song.objects.get_or_create(string=line[5])  # 曲名

            # Person以外のデータをもとにParentレコードを更新または新規作成
            # 既存のParentレコードを取得する
            existing_parent = Parent.objects.filter(
                league=league,
                year=year,
                team=team,
                participation=participation,
                song=song
            ).first()

            # 既存のParentレコードが存在する場合
            if existing_parent:
                # すでにPersonが追加されていない場合に追加
                parent.person.add(person)
            else:
                # Parentレコードが存在しない場合は新規作成
                parent = Parent.objects.create(
                    league=league,
                    year=year,
                    team=team,
                    participation=participation,
                    song=song,
                )
                parent.person.set([person])

    return render(request, 'upload.html')

mysite/myapp/templates/home.html
<!-- home.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        thead {
            position: sticky;
            top: 0;
            background-color: #f8f9fa; /* グレーの背景色 */
        }
    </style>
    <title>Form Example</title>
</head>
<body>
    <div class="container mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-row">
                <!-- セレクトボックス -->
                <div class="form-group col-md-4">
                    <label for="selectOption">検索オプション:</label>
                    <select class="form-control" id="selectOption" name="selectOption">
                        <option value="league">開催回数</option>
                        <option value="year">開催した年</option>
                        <option value="team">赤組か白組</option>
                        <option value="participation">出場回数</option>
                        <option value="person">歌手</option>
                        <option value="song">曲名</option>
                    </select>
                </div>

                <!-- テキストボックス -->
                <div class="form-group col-md-4">
                    <label for="textBox">入力:</label>
                    <input type="text" class="form-control" id="textBox" name="textBox">
                </div>

                <!-- 送信ボタン -->
                <div class="form-group col-md-4 align-self-end">
                    <button type="submit" class="btn btn-primary">検索</button>
                </div>
            </div>
        </form>

        <!-- 表示するデータがある場合のみテーブルを表示 -->
        {% if data %}
            <table class="table mt-3">
                <thead class="sticky-top">
                    <tr>
                        <th>開催回数</th>
                        <th>年</th>
                        <th>チーム</th>
                        <th>出場回数</th>
                        <th>歌手名</th>
                        <th>曲名</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data %}
                        <tr>
                            <td>{{ item.league.number }}</td>
                            <td>{{ item.year.number }}</td>
                            <td>{{ item.team.string }}</td>
                            <td>{{ item.participation.number }}</td>
                            <td>{{ item.person.all|join:', ' }}</td>
                            <td>{{ item.song.string }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>

    <!-- BootstrapのJavaScriptとjQueryのリンク -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

mysite/myapp/templates/upload.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>アップロード</title>

    <!-- Bootstrap CSS from CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body class="bg-light">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h4 class="text-center">CSVデータをアップロード</h4>
                    </div>
                    <div class="card-body">

                        <form action="{% url 'myapp:upload' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="csv">CSVファイルを選択してください</label>
                                <input type="file" class="form-control-file" name="csv">
                            </div>
                            <button type="submit" class="btn btn-primary">送信</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and Popper.js from CDN -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>